### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino' error

### ISSUE THREAD

**Issue by LunarTaku** [bes-dev/stable_diffusion.openvino#111]
i keep getting the 
```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/lunar/Desktop/stable_diffusion.openvino-master/demo_web.py", line 12, in <module>
    from stable_diffusion_engine import StableDiffusionEngine
  File "/Users/lunar/Desktop/stable_diffusion.openvino-master/stable_diffusion_engine.py", line 5, in <module>
    from openvino.runtime import Core
ModuleNotFoundError: No module named 'openvino'

```

error, any help?
OS: macos 10.15.7
Core: i7 6600U vPro
RAM: 16GB
ive tried all of the above and nothing has worked so far.

**Comment by alabasterfox** [comment]
openvino is not installed. try running:

pip3 install openvino

**Comment by LunarTaku** [comment]
> openvino is not installed. try running:
> 
> pip3 install openvino

it is installed though:
```bash
Requirement already satisfied: openvino in /usr/local/lib/python3.9/site-packages (2022.1.0)
Requirement already satisfied: numpy<1.20,>=1.16.6 in /usr/local/lib/python3.9/site-packages (from openvino) (1.19.5)
```

**Comment by alabasterfox** [comment]
Could it be that your openvino is installed under Python3.9 but your project is searching for it under Python3.11?

**Comment by oladimeji09** [comment]
were you able to solve this @LunarTaku, I ran into the same error ?
