### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Nathan-dm** [bes-dev/stable_diffusion.openvino#120]
Traceback (most recent call last):
  File "C:\211\openvino\stable_diffusion.openvino\demo.py", line 7, in <module>
    from stable_diffusion_engine import StableDiffusionEngine
  File "C:\211\openvino\stable_diffusion.openvino\stable_diffusion_engine.py", line 4, in <module>
    from openvino.runtime import Core
  File "C:\211\openvino\stable_diffusion.openvino\openvino_env\lib\site-packages\openvino\runtime\__init__.py", line 12, in <module>
    from openvino._pyopenvino import get_version
ImportError: DLL load failed while importing _pyopenvino: The specified module could not be found.

i get error, i have done all instalation steps, im using intel i5 1135G7

**Comment by Nathan-dm** [comment]
Fixed, just used this code

`pip install openvino-dev[onnx,pytorch]==2022.1.0`
