### ISSUE TITLE
RuntimeError: bad allocation in stable_diffusion_engine.py

### ISSUE THREAD

**Issue by gungwang** [bes-dev/stable_diffusion.openvino#132]
$ python demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"
Traceback (most recent call last):
  File "I:\ai\stable_diffusion.openvino\demo.py", line 83, in <module>
    main(args)
  File "I:\ai\stable_diffusion.openvino\demo.py", line 35, in main
    engine = StableDiffusionEngine(
  File "I:\ai\stable_diffusion.openvino\stable_diffusion_engine.py", line 41, in __init__
    self.unet = self.core.compile_model(self._unet, device)
  File "I:\AI\Python390\lib\site-packages\openvino\runtime\ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: bad allocation

**Comment by brmarkus** [comment]
Can you provide more details about your environment (HW and SW), please?
How have you set-up and installed the environment? Which versions have you installed?

**Comment by oscarnevarezleal** [comment]
Yeah, it happened to me as well only with device = CPU, doesn;t happen with device = GPU
11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.30 GHz, IrisXe
