### ISSUE TITLE
TypeError: unsupported operand type(s) 

### ISSUE THREAD

**Issue by dynamodan** [bes-dev/stable_diffusion.openvino#146]
I just installed on manjaro from the AUR (which builds from this git repo), and getting this error:

```
/opt/stable-diffusion-intel  python demo.py --prompt "apples and oranges in a wooden bowl"
Traceback (most recent call last):
  File "/opt/stable-diffusion-intel/demo.py", line 73, in <module>
    main(args)
  File "/opt/stable-diffusion-intel/demo.py", line 35, in main
    image = engine(
  File "/opt/stable-diffusion-intel/stable_diffusion_engine.py", line 164, in __call__
    latents = latents * self.scheduler.sigmas[0]
TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
```

**Comment by Ljuk67** [comment]
I'm getting the same on a Linux Mint 21.1:

python3 demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"
Traceback (most recent call last):
  File "/home/****/stable_diffusion.openvino/demo.py", line 83, in <module>
    main(args)
  File "/home/****/stable_diffusion.openvino/demo.py", line 41, in main
    image = engine(
  File "/home/****/stable_diffusion.openvino/stable_diffusion_engine.py", line 166, in __call__
    latents = latents * self.scheduler.sigmas[0]
TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
