### ISSUE TITLE
Web UI ?

### ISSUE THREAD

**Issue by b1tfl0w** [bes-dev/stable_diffusion.openvino#166]
Hello, thank you for this! I succesfully made it work on my Debian server on mini pc intel i5 6400t 8gb ram,  I had to add 16GB of swap file though. I can get the image in 5/6 min `32it [05:39, 10.62s/it]`
But how do I access web ui?

**Comment by brmarkus** [comment]
This repo doesn't seem to provide a Web-GUI...
There are quite a lot of online services for "Stable Diffusion" available in the internet, offering a web-ui, web-interfaces (for free or commercial).

**Comment by b1tfl0w** [comment]
oops..I discovered from the old comments that there was a file called `demo_web.py` in an old commit, so I downloaded it to the same folder as the current git:

`wget https://raw.githubusercontent.com/bes-dev/ stable_diffusion.openvino/4dd5acdaec3c7cda1bae7159168d2de4102baac1/demo_web.py`

I tried to start it but a dependency was missing:

```
streamlit run demo_web.py
Traceback (most recent call last):
File "/home/bitflow/openvino_sd/openvino_env/bin/streamlit", line 5, in <module>     from streamlit.web.cli import main
File "/home/bitflow/openvino_sd/openvino_env/lib/python3.9/site-packages/streamlit/__init__.py", line 70, in <module>     from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
File "/home/bitflow/openvino_sd/openvino_env/lib/python3.9/site-packages/streamlit/delta_generator.py", line 90, in <module>     from streamlit.elements.arrow_altair import ArrowAltairMixin
File "/home/bitflow/openvino_sd/openvino_env/lib/python3.9/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>     from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
```

I investigated the missing dependency and installed it like this:

`pip install altair==4.0`

now the demo web page seems to work:

```
streamlit run demo_web.py    
You can now view your Streamlit app in your browser.    
Network URL: http://192.168.100.104:8501   
External URL: http://xxx.xxx.xxx.xxx:8501  
10it [02:31, 15.16s/it] 
18it [02:45,  9.22s/it]
```
