### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit_drawable_canvas'

### ISSUE THREAD

**Issue by dervish54** [bes-dev/stable_diffusion.openvino#34]
There is no streamlit_drawable_canvas library in requirements.txt

```
2022-09-03 08:36:23.931 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\User\stable_diffusion.openvino-master\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\User\stable_diffusion.openvino-master\demo_web.py", line 6, in <module>
    from streamlit_drawable_canvas import st_canvas
ModuleNotFoundError: No module named 'streamlit_drawable_canvas'
  Stopping...
```

Installing streamlit_drawable_canvas  solves this problem.

**Comment by Oplkill** [comment]
The solution for you:
`pip install streamlit-drawable-canvas `
Solution for git masters is add that depence in "depence.txt"
