### ISSUE TITLE
Missing requirements for streamlit

### ISSUE THREAD

**Issue by mberg2007** [bes-dev/stable_diffusion.openvino#38]
Creating a docker image and running streamlit with demo_web.py gives the following error immediately upon entering the web app from a browser:

```
$ docker run -p 8501:8501 sdopenvino:latest

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://80.208.65.21:8501

2022-09-04 17:46:11.731 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/src/demo_web.py", line 6, in <module>
    from streamlit_drawable_canvas import st_canvas
ModuleNotFoundError: No module named 'streamlit_drawable_canvas'
```

I fixed this by running a pip install of the streamlit_drawable_canvas module. I guess this module should be part of requirements.txt?

**Comment by soten355** [comment]
I had the same error just running the demo_web.py through a virtual environment. The problem was fixed with your suggestion

`pip install streamlit_drawable_canvas`

I agree, it should be part of the requirements.txt
