### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' 

### ISSUE THREAD

**Issue by frtn7** [bes-dev/stable_diffusion.openvino#79]
I can't run the generation due to this error, but i'm sure numpy is installed

```(vin) C:\Users\frtn7\projects\stable_diffusion.openvino>python pygui.py
C:\ProgramData\Miniconda3\python.exe "C:/Users/frtn7/projects/stable_diffusion.openvino/demo.py" --prompt "a black and white 3D render of a beautiful profile face portrait of a female vegetal-dragon-cyborg, 150 mm, orchid stems, fine lace, Mandelbrot fractal, anatomical, flesh, facial muscles, cable wires, microchip, veins, arteries, full frame, microscopic, elegant, highly detailed, flesh ornate, elegant, high fashion, rim light, octane render in the style of H.R. Giger and Man Ray" --output "C:/Users/frtn7/output.png" --num-inference-steps 50 --model ShadowPower/waifu-diffusion.openvino
executing C:\ProgramData\Miniconda3\python.exe "C:/Users/frtn7/projects/stable_diffusion.openvino/demo.py" --prompt "a black and white 3D render of a beautiful profile face portrait of a female vegetal-dragon-cyborg, 150 mm, orchid stems, fine lace, Mandelbrot fractal, anatomical, flesh, facial muscles, cable wires, microchip, veins, arteries, full frame, microscopic, elegant, highly detailed, flesh ornate, elegant, high fashion, rim light, octane render in the style of H.R. Giger and Man Ray" --output "C:/Users/frtn7/output.png" --num-inference-steps 50 --model ShadowPower/waifu-diffusion.openvino
Traceback (most recent call last):
  File "C:\Users\frtn7\projects\stable_diffusion.openvino\demo.py", line 5, in <module>
    from stable_diffusion_engine import StableDiffusionEngine
  File "C:\Users\frtn7\projects\stable_diffusion.openvino\stable_diffusion_engine.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
executing C:\ProgramData\Miniconda3\python.exe "C:/Users/frtn7/projects/stable_diffusion.openvino/demo.py" --prompt "a black and white 3D render of a beautiful profile face portrait of a female vegetal-dragon-cyborg, 150 mm, orchid stems, fine lace, Mandelbrot fractal, anatomical, flesh, facial muscles, cable wires, microchip, veins, arteries, full frame, microscopic, elegant, highly detailed, flesh ornate, elegant, high fashion, rim light, octane render in the style of H.R. Giger and Man Ray" --output "C:/Users/frtn7/output.png" --num-inference-steps 50 --model ShadowPower/waifu-diffusion.openvino
Traceback (most recent call last):
  File "C:\Users\frtn7\projects\stable_diffusion.openvino\demo.py", line 5, in <module>
    from stable_diffusion_engine import StableDiffusionEngine
  File "C:\Users\frtn7\projects\stable_diffusion.openvino\stable_diffusion_engine.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by Ishm4el** [comment]
I was receiving this error earlier. I went around the problem by installing Miniconda, which worked. 
I believe I was receiving this error due Python being 3.10.~, the version that my Conda is using is 3.9; so, you if you have Python version 3.10, you can probably fix the situation by installing Python 3.9.

**Comment by UnfathomableArrest** [comment]
I am still having problems with this issue after reinstalling conda and python and assuring that numpy was installed

**Comment by frtn7** [comment]
> I am still having problems with this issue after reinstalling conda and python and assuring that numpy was installed
> 

Try to install all requirements and execute pygui.py without conda
It worked for me
