### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit'

### ISSUE THREAD

**Issue by j-uneee** [bes-dev/stable_diffusion.openvino#83]
### I do have streamlit installed (maybe incorrectly?)
`C:\ProgramData\Miniconda3\python.exe "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\demo_web.py" --prompt "egg" --output "C:/Users/(user)/Pictures/DLs/art/AI/OpenVINO/test.png" --num-inference-steps 1 --model bes-dev/stable-diffusion-v1-4-openvino
executing C:\ProgramData\Miniconda3\python.exe "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\demo_web.py" --prompt "egg" --output "C:/Users/(user)/Pictures/DLs/art/AI/OpenVINO/test.png" --num-inference-steps 1 --model bes-dev/stable-diffusion-v1-4-openvino
Traceback (most recent call last):
  File "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\demo_web.py", line 5, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\ProgramData\Miniconda3\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\pygui.py", line 80, in manager
    self.check_queue()
  File "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\pygui.py", line 112, in check_queue
    self.queue_items[ind].check()
  File "C:\Users\(user)\Desktop\my things\programming\neural net\stable_diffusion.openvino\pygui.py", line 413, in check
    self.image = Image.open(self.data.upscaled)
  File "C:\Users\(user)\AppData\Roaming\Python\Python39\site-packages\PIL\Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/(user)/Pictures/DLs/art/AI/OpenVINO/test.png'`

**Comment by SaeedBaig** [comment]
I got same error when trying to run web demo (addding screenshot)

![ai_three](https://user-images.githubusercontent.com/29703429/195247491-65e58f31-0a1a-4f09-ba8f-f36cf446fd3c.png)

**Comment by justhereforhelppp** [comment]
"pip install streamlit-drawable-canvas" worked for me, for some reason streamlit-drawable-canvas isn't in the requirements.txt of this program
(& to the mods if it's possible, could you delete this problem after it's closed because I accidentally left my name in the filepath😅)

**Comment by dronov-dmitry** [comment]
`python3.9 -m pip install streamlit-drawable-canvas`

It fix this problem for me

**Comment by zos474** [comment]
pip3 install streamlit-drawable-canvas worked for me too. Thanks for your help! By the way, I was getting one error after another (that I couldn't fix) when running Python 3.10.  I had a conda environment with 3.85 in it and used that to finally get it going (apart from this one last issue.)
