### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'tensor_format'

### ISSUE THREAD

**Issue by toptiermongoloid** [bes-dev/stable_diffusion.openvino#97]
whenever i try to run demo.py and web_demo.py, and also when i try to render images with pygui.py i always get this line of code. 
Not sure what to make of it. I had to install a bunch of other stuff after following this guide https://rentry.org/cputard due to errors, but now i have no idea of what to do next

**Comment by brmarkus** [comment]
Can you provide mode details about what and how you have installed your environment, using which OperatingSystem and which versions of e.g. Python?
You might want to create a Python-Virtual-Environment to not conflict with existing globally installed packages.

Can you try again, using a Python-virt-env (using e.g. Python v3.8) and just call `pip install -r requirements.txt`?

Example:
```
mkdir venv
python3.8 -m venv venv/
source venv/bin/activate
venv/bin/python3.8 -m pip install --upgrade pip
pip3 install -r requirements.txt
python3 demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"
```

**Comment by toptiermongoloid** [comment]
yeah, i reinstalled everything and now it works just fine, i'm not really sure what caused this issue to happen 
was using python 3.9 and windows 10

**Comment by b4zz4** [comment]
```
Traceback (most recent call last):
  File "/opt/stable-diffusion-intel/txt2img", line 74, in <module>
    main(args)
  File "/opt/stable-diffusion-intel/txt2img", line 17, in main
    scheduler = LMSDiscreteScheduler(
  File "/usr/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 406, in inner_init
    init(self, *args, **init_kwargs)
TypeError: LMSDiscreteScheduler.__init__() got an unexpected keyword argument 'tensor_format'

```

**Comment by Kobaxidze256** [comment]
I have this issue after installing with https://aur.archlinux.org/packages/stable-diffusion-intel

**Comment by SeanLyn** [comment]
Same issue in `Ubuntu 22.04.2 LTS`
Clone this github projects in PyCharm Community version.

Run the install: 
```
python -m pip install --upgrade pip
pip install openvino-dev[onnx,pytorch]==2022.3.0
pip install -r requirements.txt
```
Run 
`python demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"`
Then got this error
`TypeError: LMSDiscreteScheduler.__init__() got an unexpected keyword argument 'tensor_format'`

**Comment by Kobaxidze256** [comment]
> I have this issue after installing with https://aur.archlinux.org/packages/stable-diffusion-intel

In this case the dependencies are probably too new.
